### ISSUE TITLE
启动demo异常

### ISSUE THREAD

**Issue by liaokevin** [alibaba/SOFA#2]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by liaokevin** [comment]
logback.version 版本问题

**Comment by d342784178** [comment]
demo在哪?

**Comment by significantfrank** [comment]
使用Archetype可以创建Demo

**Comment by d342784178** [comment]
你好,
在使用demo的过程中 发现框架主要围绕ExtensionExecutor功能
其实我更关注的是ddd如何落地 想请教下是否贵团队有总结出什么指导思想
本人也有在看<<实现领域驱动设计>> 但感觉比较空洞 
希望不吝赐教

**Comment by significantfrank** [comment]
你是做哪个领域的项目

**Comment by d342784178** [comment]
现在还在学习ddd 没有固定的某个领域
只是想知道ddd思想在java中该如何落地
